#ifndef RB_PRJ_GLOBALSWITCHSETTINGS_H__
#define RB_PRJ_GLOBALSWITCHSETTINGS_H__
/**
    This file is automatically generated by the VariantGenerator.ps1 from pure::variants feature models
    DO NOT EDIT THIS FILE MANUALLY ! > please contact your SW architect !
*/


#define RBFS_AudioSystem_Standard 1
#define RBFS_AudioSystem_Bose 2

#define RBFS_Customer_DAI 1
#define RBFS_Customer_RB 2

#define RBFS_Drivetrain_AWD 1
#define RBFS_Drivetrain_FWD 2
#define RBFS_Drivetrain_RWD 3

#define RBFS_Engine_Diesel 1
#define RBFS_Engine_Gasoline 2
#define RBFS_Engine_Electric 3

#define RBFS_Gearbox_Automatic 1
#define RBFS_Gearbox_Manual 2

#define RBFS_HeadLights_Halogen 1
#define RBFS_HeadLights_Xenon 2
#define RBFS_HeadLights_LED 3

#define RBFS_Product_VMPS 1
#define RBFS_Product_MMP2 2
#define RBFS_Product_MPSP 3

#define RBFS_Project_BR223 1
#define RBFS_Project_HWREF 2

#define RBFS_Trailer_ON 1
#define RBFS_Trailer_OFF 2

#define RBFS_Winter_ON 1
#define RBFS_Winter_OFF 2


#endif /* End of multiple include protection */

