#ifndef RB_PRJ_GLOBALSETTINGS_H__
#define RB_PRJ_GLOBALSETTINGS_H__
/**
    This file is automatically generated by the VariantGenerator.ps1 from pure::variants feature models
    DO NOT EDIT THIS FILE MANUALLY ! > please contact your SW architect !
*/


#include "Cfg_MTC_ConfigurationDefines.cfg"
#include "RB_Prj_GlobalSwitchSettings.h"

#if (RBFS_BUILDCONFIG == RBFS_BUILDCONFIG_Basic)
  #define RBFS_AudioSystem   RBFS_AudioSystem_Standard
  #define RBFS_Customer   RBFS_Customer_RB
  #define RBFS_Drivetrain   RBFS_Drivetrain_FWD
  #define RBFS_Engine   RBFS_Engine_Gasoline
  #define RBFS_Gearbox   RBFS_Gearbox_Manual
  #define RBFS_Product   RBFS_Product_MPSP
  #define RBFS_Project   RBFS_Project_HWREF
#endif


#if (RBFS_BUILDCONFIG == RBFS_BUILDCONFIG_Medium)
  #define RBFS_AudioSystem   RBFS_AudioSystem_Standard
  #define RBFS_Customer   RBFS_Customer_DAI
  #define RBFS_Drivetrain   RBFS_Drivetrain_RWD
  #define RBFS_Engine   RBFS_Engine_Diesel
  #define RBFS_Gearbox   RBFS_Gearbox_Manual
  #define RBFS_Product   RBFS_Product_VMPS
  #define RBFS_Project   RBFS_Project_BR223
#endif


#if (RBFS_BUILDCONFIG == RBFS_BUILDCONFIG_Top)
  #define RBFS_AudioSystem   RBFS_AudioSystem_Bose
  #define RBFS_Customer   RBFS_Customer_RB
  #define RBFS_Drivetrain   RBFS_Drivetrain_AWD
  #define RBFS_Engine   RBFS_Engine_Electric
  #define RBFS_Gearbox   RBFS_Gearbox_Automatic
  #define RBFS_Product   RBFS_Product_MPSP
  #define RBFS_Project   RBFS_Project_HWREF
#endif


/* COMMON DEFINES (for all defined build variants) */
#define RBFS_HeadLights   RBFS_HeadLights_LED
#define RBFS_Trailer   RBFS_Trailer_ON
#define RBFS_Winter   RBFS_Winter_ON

#endif /* End of multiple include protection */

