!pragma useVerticalIf on
title State: dcom_Done_ReadOrWriteNVMBlock
start
:State machine dcom_EepromWriteByPdmState at State <b>dcom_Done_ReadOrWriteNVMBlock;
:Reset the counter l_EEPROMRetryLimit to 0
Change state machine to Init state i.e. <b>dcom_NvMGetErrorStatus_BeforeReadOrWriteRequest
Update Return Value with E_OK;
stop
