#ifndef RB_PRJ_GLOBALSETTINGS_H__
#define RB_PRJ_GLOBALSETTINGS_H__
/**
    This file is automatically generated by the VariantGenerator.ps1 from pure::variants feature models
    DO NOT EDIT THIS FILE MANUALLY ! > please contact your SW architect !
*/


#include "Cfg_MTC_ConfigurationDefines.cfg"
#include "RB_Prj_GlobalSwitchSettings.h"

#if (RBFS_BUILDCONFIG == RBFS_BUILDCONFIG_MMP2xD3xRef)
  #define RBFS_ComServices   RBFS_ComServices_CanOnly
  #define RBFS_ConfigurationType   RBFS_ConfigurationType_DEVELOP
  #define RBFS_Customer   RBFS_Customer_RB
  #define RBFS_HSWProjectVariant   RBFS_HSWProjectVariant_MMP2xDevBoard
  #define RBFS_HSWuC   RBFS_HSWuC_RenesasD3
  #define RBFS_HSWXCPSupport   RBFS_HSWXCPSupport_OFF
  #define RBFS_IgnoreComSecurityCheckResult   RBFS_IgnoreComSecurityCheckResult_OFF
  #define RBFS_IgnoreComServicesGeneration   RBFS_IgnoreComServicesGeneration_ON
  #define RBFS_IgnoreFiMGeneration   RBFS_IgnoreFiMGeneration_ON
  #define RBFS_PlantFeatures   RBFS_PlantFeatures_OFF
  #define RBFS_Product   RBFS_Product_MPSP
  #define RBFS_Project   RBFS_Project_HWREF
  #define RBFS_ThirdPartySWIntegration   RBFS_ThirdPartySWIntegration_MpspPrjThirdPartyIntegration
#endif


#if (RBFS_BUILDCONFIG == RBFS_BUILDCONFIG_VMPSxBR223)
  #define RBFS_ComServices   RBFS_ComServices_CanAndEth
  #define RBFS_ConfigurationType   RBFS_ConfigurationType_DEVELOP
  #define RBFS_Customer   RBFS_Customer_DAI
  #define RBFS_HSWProjectVariant   RBFS_HSWProjectVariant_VMPSBoard
  #define RBFS_HSWuC   RBFS_HSWuC_RenesasD5onD5ED
  #define RBFS_HSWXCPSupport   RBFS_HSWXCPSupport_ON
  #define RBFS_IgnoreComSecurityCheckResult   RBFS_IgnoreComSecurityCheckResult_OFF
  #define RBFS_IgnoreComServicesGeneration   RBFS_IgnoreComServicesGeneration_OFF
  #define RBFS_IgnoreFiMGeneration   RBFS_IgnoreFiMGeneration_OFF
  #define RBFS_PlantFeatures   RBFS_PlantFeatures_OFF
  #define RBFS_Product   RBFS_Product_VMPS
  #define RBFS_Project   RBFS_Project_BR223
  #define RBFS_Region   RBFS_Region_EUandNA
  #define RBFS_ThirdPartySWIntegration   RBFS_ThirdPartySWIntegration_DaiCoreThirdPartySWIntegration
#endif


#if (RBFS_BUILDCONFIG == RBFS_BUILDCONFIG_VMPSxBR223xPlantD5)
  #define RBFS_ComServices   RBFS_ComServices_CanAndEthUnsecured
  #define RBFS_ConfigurationType   RBFS_ConfigurationType_DEVELOP
  #define RBFS_Customer   RBFS_Customer_DAI
  #define RBFS_HSWProjectVariant   RBFS_HSWProjectVariant_VMPSBoard
  #define RBFS_HSWuC   RBFS_HSWuC_RenesasD5
  #define RBFS_HSWXCPSupport   RBFS_HSWXCPSupport_ON
  #define RBFS_IgnoreComSecurityCheckResult   RBFS_IgnoreComSecurityCheckResult_ON
  #define RBFS_IgnoreComServicesGeneration   RBFS_IgnoreComServicesGeneration_OFF
  #define RBFS_IgnoreFiMGeneration   RBFS_IgnoreFiMGeneration_OFF
  #define RBFS_PlantFeatures   RBFS_PlantFeatures_ON
  #define RBFS_Product   RBFS_Product_VMPS
  #define RBFS_Project   RBFS_Project_BR223
  #define RBFS_Region   RBFS_Region_EUandNA
  #define RBFS_ThirdPartySWIntegration   RBFS_ThirdPartySWIntegration_DaiCoreThirdPartySWIntegration
#endif


#if (RBFS_BUILDCONFIG == RBFS_BUILDCONFIG_VMPSxBR223xPlantD5ED)
  #define RBFS_ComServices   RBFS_ComServices_CanAndEthUnsecured
  #define RBFS_ConfigurationType   RBFS_ConfigurationType_DEVELOP
  #define RBFS_Customer   RBFS_Customer_DAI
  #define RBFS_HSWProjectVariant   RBFS_HSWProjectVariant_VMPSBoard
  #define RBFS_HSWuC   RBFS_HSWuC_RenesasD5onD5ED
  #define RBFS_HSWXCPSupport   RBFS_HSWXCPSupport_ON
  #define RBFS_IgnoreComSecurityCheckResult   RBFS_IgnoreComSecurityCheckResult_ON
  #define RBFS_IgnoreComServicesGeneration   RBFS_IgnoreComServicesGeneration_OFF
  #define RBFS_IgnoreFiMGeneration   RBFS_IgnoreFiMGeneration_OFF
  #define RBFS_PlantFeatures   RBFS_PlantFeatures_ON
  #define RBFS_Product   RBFS_Product_VMPS
  #define RBFS_Project   RBFS_Project_BR223
  #define RBFS_Region   RBFS_Region_EUandNA
  #define RBFS_ThirdPartySWIntegration   RBFS_ThirdPartySWIntegration_DaiCoreThirdPartySWIntegration
#endif


#if (RBFS_BUILDCONFIG == RBFS_BUILDCONFIG_VMPSxD5EDxRef)
  #define RBFS_ComServices   RBFS_ComServices_CanAndEth
  #define RBFS_ConfigurationType   RBFS_ConfigurationType_DEVELOP
  #define RBFS_Customer   RBFS_Customer_RB
  #define RBFS_HSWProjectVariant   RBFS_HSWProjectVariant_VMPSBoard
  #define RBFS_HSWuC   RBFS_HSWuC_RenesasD5onD5ED
  #define RBFS_HSWXCPSupport   RBFS_HSWXCPSupport_OFF
  #define RBFS_IgnoreComSecurityCheckResult   RBFS_IgnoreComSecurityCheckResult_OFF
  #define RBFS_IgnoreComServicesGeneration   RBFS_IgnoreComServicesGeneration_ON
  #define RBFS_IgnoreFiMGeneration   RBFS_IgnoreFiMGeneration_OFF
  #define RBFS_PlantFeatures   RBFS_PlantFeatures_OFF
  #define RBFS_Product   RBFS_Product_MPSP
  #define RBFS_Project   RBFS_Project_HWREF
  #define RBFS_ThirdPartySWIntegration   RBFS_ThirdPartySWIntegration_MpspPrjThirdPartyIntegration
#endif


#if (RBFS_BUILDCONFIG == RBFS_BUILDCONFIG_VMPSxD5EDxRefxRelease)
  #define RBFS_ComServices   RBFS_ComServices_CanAndEth
  #define RBFS_ConfigurationType   RBFS_ConfigurationType_RELEASE
  #define RBFS_Customer   RBFS_Customer_RB
  #define RBFS_HSWProjectVariant   RBFS_HSWProjectVariant_VMPSBoard
  #define RBFS_HSWuC   RBFS_HSWuC_RenesasD5onD5ED
  #define RBFS_HSWXCPSupport   RBFS_HSWXCPSupport_OFF
  #define RBFS_IgnoreComSecurityCheckResult   RBFS_IgnoreComSecurityCheckResult_OFF
  #define RBFS_IgnoreComServicesGeneration   RBFS_IgnoreComServicesGeneration_ON
  #define RBFS_IgnoreFiMGeneration   RBFS_IgnoreFiMGeneration_OFF
  #define RBFS_PlantFeatures   RBFS_PlantFeatures_OFF
  #define RBFS_Product   RBFS_Product_MPSP
  #define RBFS_Project   RBFS_Project_HWREF
  #define RBFS_ThirdPartySWIntegration   RBFS_ThirdPartySWIntegration_MpspPrjThirdPartyIntegration
#endif


/* COMMON DEFINES (for all defined build variants) */
#define RBFS_DaiDFT   RBFS_DaiDFT_OFF
#define RBFS_MTCVersion   RBFS_MTCVersion_V10p6p1p0

#endif /* End of multiple include protection */

