#ifndef RB_PRJ_GLOBALSWITCHSETTINGS_H__
#define RB_PRJ_GLOBALSWITCHSETTINGS_H__
/**
    This file is automatically generated by the VariantGenerator.ps1 from pure::variants feature models
    DO NOT EDIT THIS FILE MANUALLY ! > please contact your SW architect !
*/


#define RBFS_ComServices_CanOnly 1
#define RBFS_ComServices_CanAndEth 2
#define RBFS_ComServices_CanAndEthUnsecured 3

#define RBFS_ConfigurationType_DEVELOP 1
#define RBFS_ConfigurationType_RELEASE 2

#define RBFS_Customer_DAI 1
#define RBFS_Customer_RB 2

#define RBFS_DaiDFT_ON 1
#define RBFS_DaiDFT_OFF 2

#define RBFS_HSWProjectVariant_MMP2xDevBoard 1
#define RBFS_HSWProjectVariant_VMPSBoard 2

#define RBFS_HSWuC_RenesasD3 1
#define RBFS_HSWuC_RenesasD5 2
#define RBFS_HSWuC_RenesasD5onD5ED 3

#define RBFS_HSWXCPSupport_ON 1
#define RBFS_HSWXCPSupport_OFF 2

#define RBFS_IgnoreComSecurityCheckResult_ON 1
#define RBFS_IgnoreComSecurityCheckResult_OFF 2

#define RBFS_IgnoreComServicesGeneration_ON 1
#define RBFS_IgnoreComServicesGeneration_OFF 2

#define RBFS_IgnoreFiMGeneration_ON 1
#define RBFS_IgnoreFiMGeneration_OFF 2

#define RBFS_MTCVersion_V10p6p1p0 1

#define RBFS_PlantFeatures_ON 1
#define RBFS_PlantFeatures_OFF 2

#define RBFS_Product_VMPS 1
#define RBFS_Product_MMP2 2
#define RBFS_Product_MPSP 3

#define RBFS_Project_BR223 1
#define RBFS_Project_HWREF 2

#define RBFS_Region_EUandNA 1
#define RBFS_Region_CN 2

#define RBFS_ThirdPartySWIntegration_DaiCoreThirdPartySWIntegration 1
#define RBFS_ThirdPartySWIntegration_MpspPrjThirdPartyIntegration 2


#endif /* End of multiple include protection */

